/*
 * This file is generated by jOOQ.
 */
package jooq.com.fabridinapoli.kotlinorms;


import jooq.com.fabridinapoli.kotlinorms.tables.Customers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;
}
