
spring:
  application:
    name: kotlinorms
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/somedatabasename
    username: jdbctemplate
    password: jdbctemplate
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
