
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Current branch
        run: echo $(git branch)
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: PR number
        run: echo $(gh pr list | grep $(git branch --show-current))
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Auto-merge Dependabot PRs
        run: 'PR_NUM="$(gh pr list | grep $(git branch --show-current) | cut -f1)"; gh pr merge --auto --squash $PR_NUM'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
